### ISSUE TITLE
Add Greek language pack to Weblate

### ISSUE THREAD

**Issue by futuresound** [rob006-software/flarum-translations#1008]
Hello @rob006, could you please set up the [Greek Language pack](https://github.com/flarum-lang/greek) in Weblate. I will take care of adding all translations from the [old language pack](https://github.com/futuresound/flarum-el) that I was maintaining and continue to do so on Weblate. Thank you in advance!

Weblate username: **futuresound**

**Comment by rob006** [comment]
Done: https://weblate.rob006.net/languages/el/flarum/. You should have maintainer permissions on Weblate.

I imported translations from old repository, but you should probably review them and ensure that they're OK.

---

Releases are handled by bot, all you need is to **approve** (please do NOT merge it manually) PRs like this: https://github.com/flarum-lang/greek/pull/1
