### ISSUE TITLE
Weblate screenshot is Disabled?

### ISSUE THREAD

**Issue by thatsgolden** [rob006-software/flarum-translations#1169]
a few years ago, I uploaded a screenshot, but now I can't find a button to upload a picture, had it been closed?

if there is a reason that can not allow to uplaod picture, would you like to allow other domain pictures can be loaded under `weblate.rob006.net`? (I use markdown to import a pic from my server, but access was denied)

![image](https://github.com/rob006-software/flarum-translations/assets/96641851/0b98e15b-32b3-4698-b8d1-0fd04483e59a)

**Comment by rob006** [comment]
AFAIK uploading screenshots requires dedicated role. I can give you required permission if you want to upload screenshots. But be aware that screenshots are for other translators to help understand context of given phrase, so they should be done on English version of Flarum without any significant changes in forums look.

As for embedding images in comments - these CSP headers are set by Weblate. I don't want to mess with that, so I suggest to just paste link to image.

**Comment by thatsgolden** [comment]
> AFAIK uploading screenshots requires dedicated role. I can give you required permission if you want to upload screenshots. But be aware that screenshots are for other translators to help understand context of given phrase, so they should be done on English version of Flarum without any significant changes in forums look.

I see, thank you for the information. I've come across a situation where [a translator mentioned](https://weblate.rob006.net/translate/flarum/flarum-bbcode/zh_Hans/?q=) that the 'wrote' string in the Chinese Package was difficult to contextualize. I believe a screenshot could really help clarify its usage in this instance. Could I possibly be granted the permission? This would be help in next time we met cases like this.

**Comment by rob006** [comment]
@thatsgolden Sorry for the delay, but I just granted you permissions for uploading screenshots. But be aware that screenshots support in Weblate is very simple and it is easy to create a mess. Try to give each screenshot a meaningful description and unique file name. And probably all screenshots should be added to English language.

![3ad9511d](https://github.com/rob006-software/flarum-translations/assets/5972388/05f7102a-81d4-4bb9-9a9b-376b2d1fb5b2)
