### ISSUE TITLE
Remove redundant translations for `foskym-custom-levels` and `foskym-oauth-center`

### ISSUE THREAD

**Issue by littlegolden** [rob006-software/flarum-translations#1287]
zh-Hans is included in the extension package.

`foskym-custom-levels`
weblate: https://weblate.rob006.net/zen/flarum/foskym-custom-levels/zh_Hans/
github: https://github.com/FoskyM/flarum-custom-levels/blob/master/locale/zh-Hans.yml

`foskym-oauth-center`
weblate: https://weblate.rob006.net/projects/flarum/foskym-oauth-center/zh_Hans/
github: https://github.com/FoskyM/flarum-oauth-center/blob/main/locale/zh-Hans.yml

**Comment by rob006** [comment]
I removed translations from this repository and Weblate. But you need to manually remove existing translations from language pack (all three foskym extensions): https://github.com/flarum-lang/chinese-simplified/tree/master/locale
