### ISSUE TITLE
OK, I'm ready

### ISSUE THREAD

**Issue by Littlegolden** [rob006-software/flarum-translations#301]
So what's next? 😃 
[Chinese language pack](https://github.com/Littlegolden/flarum-lang-simplified-chinese)
[Japanese language pack](https://github.com/Littlegolden/flarum-lang-japanese)

**Comment by rob006** [comment]
I added Simplified Chinese to Weblate. I'll add Japanese tomorrow if there will be no problems with Chinese.

To move this forward:
1. Create an account at https://weblate.rob006.net/ - I'll grant you privileges to review translations. You can also start watching Flarum projects and configure your languages - you will get notifications when new string for translation will be detected.
2. You can start review existing translations - some translations are missing, other may have some errors detected by automated tests from Weblate.
3. Review and merge https://github.com/Littlegolden/flarum-lang-simplified-chinese/pull/5
4. I can configure bot to push changes from Weblate to your repo automatically, but you need to grant write access for @robbot006 user. You can do this in repository Settings > Collaborators & teams:
 ![](https://i.rob006.net/ad3a74d7.png)

**Comment by rob006** [comment]
@Littlegolden You've sent collaborate invitation to wrong account - it should be @robbot006 (I'm using separate bot account for these tasks).

https://github.com/Littlegolden/flarum-lang-simplified-chinese/pull/5 is still not merged (I could marge it myself now, but I prefer you merge it yourself after review - it is your repo after all, I don't want to mess anything ;)).

**Comment by Littlegolden** [comment]
Thank you so much ❤, I have a lot of lab reports to write these days and I will take some spare time to check my translation file for any omissions.

**Comment by rob006** [comment]
> Thank you so much heart, I have a lot of lab reports to write these days and I will take some spare time to check my translation file for any omissions.

No hurry, just avoid committing to https://github.com/Littlegolden/flarum-lang-simplified-chinese in the meantime, since it will generate nasty conflicts with https://github.com/Littlegolden/flarum-lang-simplified-chinese/pull/5.

**Comment by Littlegolden** [comment]
Is it possible to approve those "failed check" strings at once? One by one to eliminate the problem and click save to save those strings is almost killing me. 😂

**Comment by rob006** [comment]
@Littlegolden To be honest I don't know, because I never tried to blindly ignore these inspections (usually it is worth to take a look at them).

Also you don't need to click "save" button to apply this change - you can use "next" button in navigation after dismissing inspection (I have an impression that it works faster than "save").

![7573a7cf](https://user-images.githubusercontent.com/5972388/88276477-64415d00-ccdf-11ea-8b31-9420b33337cd.png)

**Comment by rob006** [comment]
@Littlegolden I imported Japanese language pack to Weblate, you should already have permissions to manage translations.

Same as for Chinese: 
1. Review and merge https://github.com/Littlegolden/flarum-lang-japanese/pull/5
2. Grant write access for @robbot006 for https://github.com/Littlegolden/flarum-lang-japanese repository (see https://github.com/rob006-software/flarum-translations/issues/301#issuecomment-632664608).

**Comment by rob006** [comment]
@Littlegolden You still need to grant write access for @robbot006 for https://github.com/Littlegolden/flarum-lang-japanese repository (see https://github.com/rob006-software/flarum-translations/issues/301#issuecomment-632664608) to enable sync for this repository.

**Comment by Littlegolden** [comment]
OMG, I forgot this

**Comment by rob006** [comment]
Closing, since everything seems to set up. Feel free to comment here if you encounter any problems.

**Comment by Littlegolden** [comment]
Hi @rikusen0335, Japanese Translation has moved to [Weblate Translate Platform](https://weblate.rob006.net/languages/ja/flarum/), you can sign up an account to continue contributing.

**Comment by rikusen0335** [comment]
Oh that's to hear that. Thank you for the information!
