### ISSUE TITLE
Bulk edit plugin?

### ISSUE THREAD

**Issue by Littlegolden** [rob006-software/flarum-translations#339]
Maybe we can have a Bulk edit plugin for Weblate?
https://github.com/WeblateOrg/weblate/commit/82f4bfcd476a27ecbb460bd45717a7c58a922ffa

**Comment by rob006** [comment]
This should be already available:

![d4fc6340](https://user-images.githubusercontent.com/5972388/88275113-1d526800-ccdd-11ea-9e26-4c6533e3f952.png)

https://weblate.rob006.net/projects/flarum/core/zh_Hans/

I'm not sure if you will be able to dismiss inspections in this way (this installation is few versions behind, so not all features may work as described in Weblate docs), but it should work for changing status to approved. 

BTW: I still recommend browse this manually - original strings for some of extensions were changed and translations may be outdated in some cases.

**Comment by Littlegolden** [comment]
![image](https://user-images.githubusercontent.com/35162802/88278756-848c0e80-cd15-11ea-8020-1dfa60aba063.png)

I don’t have that function. Is it because of the permission?

**Comment by rob006** [comment]
> I don’t have that button. Is it because of the permission?

Probably. :confused:  On quick look I don't see any permission that could be related to this option, and I prefer to avoid giving you full admin on this project only because of this. I'll check this more closely on the weekend.

**Comment by Littlegolden** [comment]
no problem, take your time~

**Comment by rob006** [comment]
@Littlegolden This option should be available since now, let me know if you find any problems - I adjusted permissions manually, hope I didn't messed up anything :P.

**Comment by Littlegolden** [comment]
Thank you~
