### ISSUE TITLE
【Move】Littlegolden/* to FFans/*

### ISSUE THREAD

**Issue by Littlegolden** [rob006-software/flarum-translations#419]
The repo `littlegolden/flarum-lang` Chinese & Japanese both have been moved to `FFans/lang`, weblate need a update, thanks~

https://github.com/FFans/lang-japanese

https://github.com/FFans/lang-simplified-chinese

**Comment by rob006** [comment]
You need to grant write access for @robbot006 user for these repos (same as in https://github.com/rob006-software/flarum-translations/issues/301).

**Comment by Littlegolden** [comment]
I forgot that hahaha

**Comment by rob006** [comment]
OK, it should work now.
