### ISSUE TITLE
Removing translation files of the-turk extensions from weblate

### ISSUE THREAD

**Issue by DursunCanPoyraz** [rob006-software/flarum-translations#425]
- Flarum/the-turk-diff (Türkçe) https://github.com/the-turk/flarum-diff/blob/master/locale/tr.yml
- Flarum/the-turk-edit-notifications (Türkçe) https://github.com/the-turk/flarum-edit-notifications/blob/master/locale/tr.yml
- Flarum/the-turk-extended-appearance (Türkçe) https://github.com/the-turk/flarum-extended-appearance/blob/master/locale/tr.yml
- Flarum/the-turk-fancybox (Türkçe) https://github.com/the-turk/flarum-ext-fancybox/blob/master/locale/tr.yml
- Flarum/the-turk-mathren (Türkçe) https://github.com/the-turk/flarum-mathren/blob/v03/locale/tr.yml
- Flarum/the-turk-password-strength (Türkçe) https://github.com/the-turk/flarum-password-strength/blob/master/locale/tr.yml
- Flarum/the-turk-quiet-edits (Türkçe) https://github.com/the-turk/flarum-quiet-edits/blob/master/locale/tr.yml
- Flarum/the-turk-regrole (Türkçe) https://github.com/the-turk/flarum-regrole/blob/master/locale/tr.yml
- Flarum/the-turk-stargazing-theme (Türkçe) https://github.com/the-turk/flarum-stargazing-theme/blob/master/locale/tr.yml
- Flarum/the-turk-welcome-widgets (Türkçe) https://github.com/the-turk/flarum-welcome-widgets/blob/master/locale/tr.yml

**Comment by rob006** [comment]
If translations are included in the extension, wouldn't be better to remove them from Weblate (so they won't affect progress widgets)? I don't see the point in duplicating translations in language pack.

**Comment by DursunCanPoyraz** [comment]
You are right.
