### ISSUE TITLE
Georgian language

### ISSUE THREAD

**Issue by B3K4682** [rob006-software/flarum-translations#442]
Hello, i want to make new translate (Georgian). how to make it?

**Comment by rob006** [comment]
I could enable Georgian language on https://weblate.rob006.net/projects/flarum/, but this is only a first step. You would need to create repository with language pack on GitHub, configure exporting translations from Weblate, and publish your composer package on https://packagist.org/. AFAIK there is no step-by-step instruction how to do this, so it can be problematic if you have no experience with Composer/GitHub.

**Comment by B3K4682** [comment]
I have already learned how to create repository and publish my package this :)

**Comment by rob006** [comment]
I've added Georgian language in Weblate, you should already be able to translate: https://weblate.rob006.net/languages/ka/flarum/
I can grant you manager permissions for this language, but I need to know your Weblate username.

When you create GitHub repo with your language pack, add write access for @robbot006 user, I will enable exporting translations from Weblate to your repository. You can find some instructions about it [here](https://github.com/rob006-software/flarum-translations/issues/301#issuecomment-632664608).

**Comment by B3K4682** [comment]
In my country it is 1:14 am so I have to go to bed. When I wake up I will definitely do it

**Comment by B3K4682** [comment]
I invited @rob006 user to my repo

**Comment by rob006** [comment]
@B3K4682 It looks like everything is working now, and translations are exported to your language pack: https://github.com/B3K4682/lang-georgian/commits/main. You may take a look at [wiki](https://github.com/B3K4682/lang-georgian/commits/main) if you have any questions.

Good look with your language pack  :+1: . Don't forget to create tag for stable release and announce your extension at  https://discuss.flarum.org/t/languages
