### ISSUE TITLE
Add support for French language pack

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#466]
https://github.com/flarum/core/issues/2090#issuecomment-781888749
https://github.com/qiaeru/lang-french

**Comment by rob006** [comment]
I'll try to add language to Weblate and import existing translations from https://github.com/qiaeru/lang-french this evening.

/cc @qiaeru

**Comment by qiaeru** [comment]
Thanks, I planned to open a PR but you're faster than light! 😉

I registered on https://weblate.rob006.net/user/Qiaeru/ and robbot006 has been added to have access to my repo (the invite is still pending).

Everything's okay?

**Comment by rob006** [comment]
It looks fine. I'll let you know if I encounter any problem.

**Comment by rob006** [comment]
It looks like everything works and translations are exported from Weblate to your language pack. I assigned you to French language pack maintainer role on Weblate, so you should have additional privileges, like ability to mark translations as verified and trigger commits. Take a look at [FAQ](https://github.com/rob006-software/flarum-translations/wiki) and let me know if you have any questions. 
Tomorrow there should be available translation status for French language at https://rob006-software.github.io/flarum-translations/status/fr.md - you may use it to find the most popular extensions to translate.
