### ISSUE TITLE
Add Sinhala language

### ISSUE THREAD

**Issue by naDevi** [rob006-software/flarum-translations#506]
I registered account on https://weblate.rob006.net/ but "add new language" button grayed out. Is it possible to add "Sinhala (si)" language for all components?

Update instance to v4.5.2 or newer and add to weblate "Discover" page https://weblate.org/en/discover/

Why this instance doesn't host under flarum.org subdomain?

**Comment by rob006** [comment]
Flarum relies on language packs, which are Composer packages. Adding language to Weblate is not enough, you still need Composer package and maintainer to review translations and tag new releases. If you have such package, here are steps to add new language to Weblate: https://github.com/rob006-software/flarum-translations/wiki/How-to-start

> Why this instance doesn't host under flarum.org subdomain?

This is community initiative, I'm not affiliated with Flarum org.

**Comment by naDevi** [comment]
Thank you for the details and your effort to maintain the instance otherwise we have to do that on offline environment.

>If you have such package, here are steps to add new language to Weblate: https://github.com/rob006-software/flarum-translations/wiki/How-to-start

I guess it is ok to use gitlab repository. i saw you've account in it https://gitlab.com/rob006 and will try to provide necessary details soon (within some hrs)

**Comment by rob006** [comment]
> I guess it is ok to use gitlab repository. i saw you've account in it https://gitlab.com/rob006 and will try to provide necessary details soon (within some hrs)

I would prefer GitHub - so far there were no GitLab-based language packs and I'm not sure what kind of problems may pop up. But if you want to use GitLab, please grant write permissions to https://gitlab.com/robbot006 - I don't want to use my main account for pushing updates.

**Comment by naDevi** [comment]
Hi @rob006 
I'm bit confused. What should i use to store in new repo local folder? i couldn't find source language in weblate instance to download or copy this? https://github.com/rob006-software/flarum-translations/tree/master/sources otherwise does that folder contents generate/update from weblate translation activities? 🤔

https://github.com/rob006-software/flarum-lang-polish

**Comment by rob006** [comment]
You don't need to copy anything from this repo. Translations are exported automatically by bot from this repo (managed by Weblate) to your language pack. All you need is basic skeleton - `composer.json`, `extend.php` and `locale/config.js`. All `locale/*.yml` files will be generated by bot after subsplit setup.

**Comment by naDevi** [comment]
@rob006 Added your gitlab account then now you have necessary access 😊

>https://github.com/rob006-software/flarum-translations/wiki/How-to-start

(weblate account username same as its account name)

**Comment by rob006** [comment]
OK, it seems to work - language [is available on Weblate](https://weblate.rob006.net/languages/si/flarum/) and [translations are exported to language pack repo](https://gitlab.com/flarum-sinhala/language-pack/-/commit/4d1d88f1ce403ce39e4c33465f23c0089a930f62).

Note that you need to register your language pack at https://packagist.org/ and tag new release in order to make it visible by `composer require` command.

**Comment by rob006** [comment]
I'm closing this issue, since it looks like there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).

**Comment by naDevi** [comment]
@rob006 sorry, i was bit busy. registered language pack at [packagist](https://packagist.org/packages/flarum-sinhala/language-pack) and started discussion for it on flarum. still have to do anything? 😆

Thank you for the help to set-up language pack and keep maintain the weblate instance for everyone 😊

**Comment by rob006** [comment]
> still have to do anything?

No, it should be enough. Just remember to tag new release when you made new translations in the future - by default Composer installs only stable releases from tags, so if you translate something now, Composer will still install old `v0.1.0` version and ignore all new translations. You need to tag `v0.1.1` to mark new translations as stable.

You may also want o set up auto update, so Packagist will detect new releases faster: https://packagist.org/about#how-to-update-packages
