### ISSUE TITLE
Latvian language 

### ISSUE THREAD

**Issue by edevrob** [rob006-software/flarum-translations#546]
Repo: https://github.com/edevrob/flarum-lang-latvian
Title: Latvian
Code: LV

Webplate user: edevrob

**Comment by rob006** [comment]
Latvian language is available on Weblate: https://weblate.rob006.net/languages/lv/flarum/
You should also have maintainer permissions.

**Comment by rob006** [comment]
I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).
