### ISSUE TITLE
Estonian language integration

### ISSUE THREAD

**Issue by aprold** [rob006-software/flarum-translations#550]
Please add Estonian language to the list of supported languages.

Language pack repository: [https://github.com/aprold/flarum-lang-estonian](https://github.com/aprold/flarum-lang-estonian)
Language name: Estonian
Weblate user: aprold

**Comment by rob006** [comment]
@aprold You need to grant write permission for @robbot006 in your repo.

**Comment by rob006** [comment]
OK, everything should be set up, good luck with your language pack. I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).
