### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by theimerj** [rob006-software/flarum-translations#559]
Hello, I would like to add czech translation package for Flarum.

Link to package: [https://github.com/madnest/flarum-lang-czech](https://github.com/madnest/flarum-lang-czech)
Language name: Czech
Language code: cs

Weblate user: theimerj

Thank you very much for doing this.

**Comment by rob006** [comment]
Done: https://weblate.rob006.net/languages/cs/flarum/

I'm closing this issue, since it seems there is nothing more to do here. But if you have any questions, feel free to ask here or on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate).

**Comment by rob006** [comment]
BTW: These files were ignored, since these extensions are no longer supported in Flarum 1.0. You can safely remove these files from your language pack:

```
flarum-auth-facebook.yml
flarum-auth-github.yml
flarum-auth-twitter.yml
```
