### ISSUE TITLE
Move to Flarum-lang project

### ISSUE THREAD

**Issue by Littlegolden** [rob006-software/flarum-translations#579]
Thank you rob~ https://github.com/flarum-lang/chinese-simplified

**Comment by luceos** [comment]
Hi @Littlegolden,

We've discussed options with migrating existing translation packs a bit and the best way to keep git history is by you transfering your existing repository over to flarum-lang. You can so from the settings page of the repository and looking for the Transfer section, see:

![image](https://user-images.githubusercontent.com/504687/121413474-01dc6400-c966-11eb-8229-5acdae1e77e3.png)


You will then need to confirm your choice with the repository name and provide the organisation/recipient which would be `flarum-lang`. If all is well, the repository can then be accepted by someone on the team.

Let me know if you have any issues with this process, I'll gladly talk you through it!

Thank you,

Daniël

**Comment by rob006** [comment]
@Littlegolden Can you grant owner permissions for your repo to @luceos? Then he should be able to transfer repository to new org - it may be simpler in that way.

**Comment by Littlegolden** [comment]
@rob006 @luceos ok, I have sent the invitation

**Comment by luceos** [comment]
Project transferred.

**Comment by Littlegolden** [comment]
Thank you luceos, and I think it would be better if I could get admin access on this repo?

**Comment by luceos** [comment]
Whoops, done!
