### ISSUE TITLE
Move Sinhala language pack to Flarum-lang project

### ISSUE THREAD

**Issue by sayuri-gi** [rob006-software/flarum-translations#586]
@rob006 Recently i received private message from @GreXXL about [flarum-lang](https://github.com/flarum-lang) then you may need to revoke existing gitlab connection and set-up with https://github.com/sayuri-gi/sinhala
I already sent email about this change but i thought github repository issue list is convenient and easy for you.

**Comment by rob006** [comment]
I will change configuration when you move your repo to `flarum-lang` org. For the time being, please do not remove or archive https://gitlab.com/flarum-sinhala/language-pack.


BTW: `locale/config.js` is missing in new repo. Is there any reason why you don't move all commit history from https://gitlab.com/flarum-sinhala/language-pack to new repository on GitHub?

**Comment by sayuri-gi** [comment]
>BTW: locale/config.js is missing in new repo. Is there any reason why you don't move all commit history from https://gitlab.com/flarum-sinhala/language-pack to new repository on GitHub?

Sorry didn't notice it `(locale/config.js)`. you can set-up weblate sync to new repository

>Is there any reason why you don't move all commit history from https://gitlab.com/flarum-sinhala/language-pack to new repository on GitHub?

I didn't care about it much and no special reason. It'll remain as it with packagist (there're few persons get pack from it so i dont want to bother) and new translation will automatically sync to it from github repository. I also maintain one more mirror in [gitee.com](https://gitee.com/sayuri-gi/language-pack)
