### ISSUE TITLE
Move Tamil language pack to Flarum-lang project

### ISSUE THREAD

**Issue by sayuri-gi** [rob006-software/flarum-translations#598]
@rob006 this's a new language pack for tamil (ta) language https://github.com/flarum-lang/tamil then please add this language to weblate, set-up sync and set proofreader permission for `eYM3` and `sayuri` weblate users.

Default maintainer - https://github.com/eYM3

**Comment by rob006** [comment]
Done: https://weblate.rob006.net/languages/ta/flarum/

Good luck with your language pack.

**Comment by sayuri-gi** [comment]
Thank you for the support to the flarum community and contributors 😊
