### ISSUE TITLE
Add `studosi-flarum/flarum-lang-croatian`

### ISSUE THREAD

**Issue by studosi-flarum** [rob006-software/flarum-translations#732]
Hello, I'm creating a Croatian language pack using your template, please add it:

https://github.com/studosi-flarum/flarum-lang-croatian

**Comment by rob006** [comment]
Have you considered moving this language pack under https://github.com/flarum-lang org? You can read more about it [here](https://discuss.flarum.org/d/27519-the-flarum-language-project).

**Comment by rob006** [comment]
@studosi-flarum Just to make it clear: you want to delay migration to Weblate until you translate everything? Translating through Weblate should be simpler, so I suggest to import existing translations to Weblate (I can do this) and then continue translations through Weblate.

**Comment by rob006** [comment]
@studosi-flarum Any progress with this?

**Comment by rob006** [comment]
Closing, since there is no response since over 2 months.

**Comment by rob006** [comment]
Croatian language pack is now available under @flarum-lang:
Repository: https://github.com/flarum-lang/croatian
Weblate: https://weblate.rob006.net/languages/hr/flarum/

You can continue your work there (existing translations are already imported to Weblate).
