### ISSUE TITLE
Hungarian translations are approved but the maintainer is unreachable and the translations are wrong

### ISSUE THREAD

**Issue by urbalazs** [rob006-software/flarum-translations#778]
@meskobalazs and I am very active translators in Hungary. We would like to fix the existing translations and finish the missing ones. meskobalazs added many suggestions to already approved translations, but the current maintainer didn't response yet.

Can you please remove the approved status from all Hungarian translations OR give approver permission to me (urbalazs) and meskobalazs?

**Comment by rob006** [comment]
@Rebootcodesoft Any comment on this? There is over 180 suggestions for Hungarian: https://weblate.rob006.net/languages/hu/flarum/search/?offset=&q=has%3Asuggestion&sort_by=-priority%2Cposition&checksum=

@urbalazs @meskobalazs If you have Weblate account, you should be able to translate directly, you don't need to use suggestions (although it is preferred option if you're not sure that proposed translation is correct).

**Comment by Rebootcodesoft** [comment]
@urbalazs @meskobalazs You can't edit translations with status approved after login?

**Comment by Rebootcodesoft** [comment]
@urbalazs @meskobalazs Miért van szükség mindent átírni magázó módba? Ha szeretnétek magázó módot, szerintem jobb lenne erre egy külön kiadás, nem?

**Comment by meskobalazs** [comment]
@Rebootcodesoft Approval and modification of approved strings require special permission, which we don't have.

Ami pedig a fordítást illeti, ha meg tudjuk oldani, hogy legyen külön tegező és önöző (nem magázó), akkor részemről rendben van, de általában ezzel gond szokott lenni, a legtöbb platform egyetlen fordítás engedélyez nyelvenként. De ez utóbbit preferáljuk, mert a szoftverek túlnyomó többsége nem tegezi a felhasználót.

**Comment by Rebootcodesoft** [comment]
Rendben. Akkor jóváhagyom jövő hét folyamán a javaslatokat ( néhányat már megtettem). Majd meglátjuk lesz-e tegező mód külön. Köszi hogy jelezted, nem volt időm követni :)

**Comment by meskobalazs** [comment]
@urbalazs we can close this issue for now

**Comment by rob006** [comment]
I don't speak Hungarian, could you summaries conclusion from this discussion? I could add more maintainers to Weblate, but I need to make sure that @Rebootcodesoft is fine with that - with multiple maintainers it is easy to introduce inconsistencies in translations.

**Comment by Rebootcodesoft** [comment]
The misunderstanding came from not seeing the suggestions. 
We discussed whether the formal / informal address should be used.
You can add more maintainers to Weblate, that's fine.

**Comment by rob006** [comment]
@urbalazs @meskobalazs Sorry for the delay, but now you're both maintainers on Weblate (in addition to @Rebootcodesoft), so you should be able to edit verified translations. I hope you guys will discuss internally some conventions and rules to avoid conflicts and misunderstandings.
