### ISSUE TITLE
Serbian language pack

### ISSUE THREAD

**Issue by bryantmilan** [rob006-software/flarum-translations#824]
Link to repository [https://github.com/bryantmilan/lang-serbian](https://github.com/bryantmilan/lang-serbian).
Weblate username: bryantmilan

**Comment by rob006** [comment]
OK, it should work now: https://weblate.rob006.net/languages/sr/flarum/. I imported existing translations from https://github.com/bryantmilan/lang-serbian and https://github.com/zmih106/flarum-lang-serbian-latin.

You should have maintainer permissions on Weblate, so you can star reviewing translations and marking them as verified. Take a look at [wiki](https://github.com/rob006-software/flarum-translations/wiki), you can find some hints about Weblate features and workflow suggestions.
