### ISSUE TITLE
Review language packs

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#919]
https://rob006-software.github.io/flarum-translations/status/language-packs.html

 - [x] [Arabic](https://github.com/neerugupta/flarum-lang-arabic) - https://github.com/rob006-software/flarum-translations/issues/920
 - [x] [Azerbaijani](https://github.com/flarum-lang/azerbaijani) - https://github.com/flarum-lang/azerbaijani/pull/1
 - [x] [Bengali](https://github.com/flarum-lang/bengali) - https://github.com/flarum-lang/bengali/pull/1
 - [x] [Chinese (Simplified)](https://github.com/flarum-lang/chinese-simplified) - https://github.com/flarum-lang/chinese-simplified/pull/13
 - [x] [Czech](https://github.com/madnest/flarum-lang-czech) - https://github.com/rob006-software/flarum-translations/issues/921
 - [x] [Danish](https://github.com/flarum-lang/danish) - https://github.com/flarum-lang/danish/pull/1
 - [x] [Dutch](https://github.com/flarum-lang/dutch) - https://github.com/flarum-lang/dutch/pull/2
 - [x] [Estonian](https://github.com/aprold/flarum-lang-estonian) - https://github.com/rob006-software/flarum-translations/issues/923
 - [x] [Finnish](https://github.com/flarum-lang/finnish) - https://github.com/flarum-lang/finnish/pull/1
 - [x] [French](https://github.com/flarum-lang/french) - https://github.com/flarum-lang/french/pull/36
 - [x] [Georgian](https://github.com/flarum-lang/georgian) (no maintainer) - https://github.com/flarum-lang/georgian/pull/1
 - [x] [German](https://github.com/flarum-lang/german) - https://github.com/flarum-lang/german/pull/50
 - [x] [Hebrew](https://github.com/icecore2/Flarum-hebrew) - https://github.com/rob006-software/flarum-translations/issues/924
 - [x] [Hindi](https://github.com/flarum-lang/hindi) - https://github.com/flarum-lang/hindi/pull/3
 - [x] [Hungarian](https://github.com/flarum-lang/hungarian) - https://github.com/flarum-lang/hungarian/pull/1
 - [x] [Italian](https://github.com/flarum-lang/italian)
 - [x] [Japanese](https://github.com/FFans/lang-japanese) - https://github.com/rob006-software/flarum-translations/issues/925
 - [x] [Korean](https://github.com/flarum-lang/korean) - https://github.com/flarum-lang/korean/pull/1
 - [x] [Latvian](https://github.com/edevrob/flarum-lang-latvian) - https://github.com/rob006-software/flarum-translations/issues/928
 - [x] [Lithuanian](https://github.com/flarum-lang/lithuanian) - https://github.com/flarum-lang/lithuanian/pull/1
 - [x] [Malayalam](https://github.com/flarum-lang/malayalam) - https://github.com/flarum-lang/malayalam/pull/1
 - [x] [Persian](https://github.com/flarum-lang/persian) - https://github.com/flarum-lang/persian/pull/3
 - [x] [Polish](https://github.com/rob006-software/flarum-lang-polish)
 - [x] [Portuguese](https://github.com/flarum-lang/portuguese) - https://github.com/flarum-lang/portuguese/pull/3
 - [x] [Portuguese (Brazil)](https://github.com/flarum-lang/brazilian) - https://github.com/flarum-lang/brazilian/pull/2
 - [x] [Russian](https://github.com/flarum-lang/russian)
 - [x] [Serbian](https://github.com/bryantmilan/lang-serbian) - https://github.com/rob006-software/flarum-translations/issues/929
 - [ ] [Sinhala](https://github.com/flarum-lang/sinhala)
 - [x] [Slovak](https://github.com/flarum-lang/slovak) - https://github.com/flarum-lang/slovak/pull/2
 - [x] [Spanish](https://github.com/flarum-lang/spanish)
 - [x] [Swedish](https://github.com/flarum-lang/swedish) - https://github.com/flarum-lang/swedish/pull/1
 - [x] [Tamil](https://github.com/flarum-lang/tamil) - https://github.com/flarum-lang/tamil/pull/3
 - [x] [Telugu](https://github.com/flarum-lang/telugu) - https://github.com/flarum-lang/telugu/pull/2
 - [x] [Thai](https://github.com/flarum-lang/thai) - https://github.com/flarum-lang/thai/pull/2
 - [x] [Turkish](https://github.com/flarum-lang/turkish) - https://github.com/flarum-lang/turkish/pull/3
 - [x] [Uzbek](https://github.com/flarum-lang/uzbek) - https://github.com/flarum-lang/uzbek/pull/4
 - [x] [Vietnamese](https://github.com/flarum-lang/vietnamese) - https://github.com/flarum-lang/vietnamese/pull/2

**Comment by shavy4452** [comment]
Hi @rob006 , i would like to contribute in Hindi package of the extension.

**Comment by rob006** [comment]
@shavy4452 You can do this here: https://weblate.rob006.net/languages/hi/flarum/ (you need to create an account).
