### ISSUE TITLE
Arabic language pack in unmaintained?

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#920]
@neerugupta Do you still maintain https://github.com/neerugupta/flarum-lang-arabic? I can see that there were no release since over a year, despite new translations contributed by community. If you don't have time to maintain this language pack, please let me know. The best course of action would be to migrate your language pack under https://github.com/flarum-lang org, then it will be easier to maintain this repository and I could easily help with some minor issues.

**Comment by neerugupta** [comment]
@rob006 Yes, please migrate this language pack under https://github.com/flarum-lang. Let me know what is required to be done from my end. Thanks.

**Comment by rob006** [comment]
@neerugupta Please go to https://github.com/neerugupta/flarum-lang-arabic/settings and transfer repository to my account (`rob006`), I'll handle the rest.

**Comment by rob006** [comment]
@neerugupta Repo has been migrated: https://github.com/flarum-lang/arabic and new extensions has been created on Packagist: https://packagist.org/packages/flarum-lang/arabic. I suggest to mark https://packagist.org/packages/neerugupta/flarum-lang-arabic as abandoned and point to new package as a replacement.

Let me know if you will have any questions or problems.
