### ISSUE TITLE
Danish language pack is unmaintained?

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#922]
@DeliciousDanny @davwheat You're both marked as maintainers of https://github.com/flarum-lang/danish, but there are no translations in this repo. Do you still want to maintain this language pack?

Also, @davwheat it looks like you don't have maintainer permissions on Weblate, only on GitHub. Do you want to have these additional permissions on Weblate?

**Comment by davwheat** [comment]
I completely forgot it existed to be honest. If you throw Weblate perms on me, I'll start translating :)

**Comment by rob006** [comment]
@davwheat Done.

**Comment by rob006** [comment]
@davwheat Since you want to main this language pack, I'm closing this issue. In case of any questions, let's continue in https://github.com/flarum-lang/danish/pull/1.
