### ISSUE TITLE
Hebrew language pack in unmaintained?

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#924]
@icecore2 Do you still maintain https://github.com/icecore2/Flarum-hebrew? I can see that there were no release since almost a year, despite the fact that new translations are available in `master` branch. If you don't have time to maintain this language pack, please let me know. The best course of action would be to migrate your language pack under https://github.com/flarum-lang org, then it will be easier to maintain this repository and I could easily help with some minor issues.

**Comment by icecore2** [comment]
Hey, I'll migrate it soon as possible. Thanks!

**Comment by icecore2** [comment]
Done.

**Comment by rob006** [comment]
@icecore2 I moved repository, adjusted `composer.json`, removed outdated translations and fixed date translations. I suggest to:

1. Merge this PR: https://github.com/flarum-lang/hebrew/pull/4
2. Approve this PR, so new major release will be tagged: https://github.com/flarum-lang/hebrew/pull/3
3. Mark https://packagist.org/packages/flabrew/flabrew as abandoned and point to https://packagist.org/packages/flraum-lang/hebrew as replacement, so people will migrate no new package

**Comment by rob006** [comment]
I released 2.0.1, because I made a typo in package name - it is fixed now and new package is available on Packagist: https://packagist.org/packages/flarum-lang/hebrew

Let me know if you find any problems.
