### ISSUE TITLE
2 concurrent Japanese language packs

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#925]
Currently we have 2 Japanese language packs for Flarum:

1. https://github.com/FFans/lang-japanese - this was originally integrated with Weblate, but right now it is abandoned in practice (no support for Flarum 1.x).
2. https://github.com/flarum-lang/japanese - this is official repository for Japanese language pack.

First repository has more translations and it is already on Weblate, but second is more up-to-date. I suggest to:

1. Import all translations from https://github.com/flarum-lang/japanese to Weblate
2. Start exporting translations from Weblate to https://github.com/flarum-lang/japanese
3. Make @takumi9942 new maintainer for Japanese language on Weblate

@takumi9942 @littlegolden @rikusen0335 What do you think?

**Comment by takumi9942** [comment]
Thanks for your good suggestion!
I agree with your idea and wants to integrate with Weblate.
Could you provide me the documentation if it exists?
(I'm not familiar with Weblate...)

Additionaly, Is it possible to import only reviewed translations at step2.
(I want to set all translations in Weblate as "waiting for review" firstly.)
Translations in the Weblate contains some strange words, so I want review them before importing.

**Comment by rob006** [comment]
I can import your translations to Weblate and mark all old translations in Weblate as unverified, so you would be able to review them. But translations will be exported to language pack regardless of its status on Weblate, so these unverified translations also will be exported to https://github.com/flarum-lang/japanese. But it should not be a big deal - you could delay releasing new version until you verify all translations on Weblate - any change on Weblate will be synced with repository.

Some useful links about Weblate instance:
https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate
https://github.com/rob006-software/flarum-translations/wiki/How-to-start
https://github.com/rob006-software/flarum-translations/wiki/Features

**Comment by takumi9942** [comment]
Thank you for your quick responce and great documentation!

> translations will be exported to language pack regardless of its status on Weblate

OK, I understood how it works :)
(I will delay releasing until reviewing exsisting translation)

Could you import my translation [flarum-lang/japanese](https://github.com/flarum-lang/japanese) to Weblate and set my account as a maintener?
I created the Weblate account with the same username as Github.

**Comment by rob006** [comment]
@takumi9942 Done: https://weblate.rob006.net/languages/ja/flarum/

I also enabled automatic release PRs generated by bot: https://github.com/flarum-lang/japanese/pull/9 - you can just approve this PR when you will be ready to release. You can read more about it on forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76

I'm closing this issue, but if you have any further questions, feel free to ask here.
