### ISSUE TITLE
Latvian language pack is unmaintained?

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#928]
@edevrob Do you still maintain https://github.com/edevrob/flarum-lang-latvian? I can see that there were no release since over a year,. If you don't have time to maintain this language pack, please let me know. The best course of action would be to migrate your language pack under https://github.com/flarum-lang org, then it will be easier to maintain this repository and I could easily help with some minor issues.

**Comment by edevrob** [comment]
@rob006  Hey! I still keep eye on it, but haven't updated. But i think right thing to do would be migrating to https://github.com/flarum-lang, as you suggested.

**Comment by rob006** [comment]
Repository has been transferred: https://github.com/flarum-lang/latvian and new Composer package has been registered: https://packagist.org/packages/flarum-lang/latvian. I suggest to mark https://packagist.org/packages/edevrob/flarum-lang-latvian as abandoned and point to new package, to signalize users that they should migrate to new one. 

Also, I enabled automatic release pull requests on new repository. When bot detects new translations, it will open an PR with changelog draft. You can read more about it on forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76

**Comment by edevrob** [comment]
Done! @rob006
