### ISSUE TITLE
Interface translation and some extensions | AR

### ISSUE THREAD

**Issue by medelinor-1** [rob006-software/flarum-translations#958]
Hello
On the following link in Google Drive you will find a YML file containing a percentage of the translation

[https://drive.google.com/file/d/19avWrXjOx4kDIEUWgJq-dmMXKi42G1xe/view?usp=sharing](https://drive.google.com/file/d/19avWrXjOx4kDIEUWgJq-dmMXKi42G1xe/view?usp=sharing)

**Comment by rob006** [comment]
*Context: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/93*

Hmm, I though you will have this in separate files with names following Flarum convention for translations. At this state it will be quite hard to import this using my script. The fact that in this file there are translations for things already translated at https://weblate.rob006.net/languages/ar/flarum/ is also problematic. I know that this will be a lot of work, but I think that the best course of action would be to insert these translations manually in Weblate. 

/cc @neerugupta

**Comment by rob006** [comment]
I'm closing this, since there is nothing that can be done in this matter in this repo. @medelinor-1 if you want to track progress, you can create issue in https://github.com/flarum-lang/arabic (unfortunately I can' transfer this issue there).
