### ISSUE TITLE
Add more language packs (without maintainer)?

### ISSUE THREAD

**Issue by rob006** [rob006-software/flarum-translations#977]
- [x] https://github.com/flarum-lang/spanish-argentina
- [x] https://github.com/flarum-lang/sardinian
- [x] https://github.com/flarum-lang/asturian
- [x] https://github.com/flarum-lang/uyghur
- [x] https://github.com/flarum-lang/nepali
- [x] https://github.com/flarum-lang/kurdish
- [x] https://github.com/flarum-lang/irish
- [x] https://github.com/flarum-lang/armenian
- [x] https://github.com/flarum-lang/occitan
- [x] https://github.com/flarum-lang/serbian-latin (blocked by https://github.com/rob006-software/flarum-translations/issues/1052)
- [x] https://github.com/flarum-lang/kannada
- [x] https://github.com/flarum-lang/punjabi
- [x] https://github.com/flarum-lang/tagalog
- [x] https://github.com/flarum-lang/khmer
- [x] https://github.com/flarum-lang/urdu
- [x] https://github.com/flarum-lang/burmese
- [x] https://github.com/flarum-lang/afrikaans
- [x] https://github.com/flarum-lang/welsh
- [x] https://github.com/flarum-lang/kabyle
- [x] https://github.com/flarum-lang/icelandic
- [x] https://github.com/flarum-lang/macedonian
- [x] https://github.com/flarum-lang/breton
- [x] https://github.com/flarum-lang/filipino
- [x] https://github.com/flarum-lang/belarusian
- [x] https://github.com/flarum-lang/marathi
- [x] https://github.com/flarum-lang/slovenian
- [x] https://github.com/flarum-lang/esperanto
- [x] https://github.com/flarum-lang/norwegian-nynorsk
- [x] https://github.com/flarum-lang/norwegian-bokmal
- [x] https://github.com/flarum-lang/albanian
- [x] https://github.com/flarum-lang/croatian
- [x] https://github.com/flarum-lang/bulgarian

**Comment by rob006** [comment]
We could also add the most popular languages from https://hosted.weblate.org/projects/weblate/application/ (with more than 5-10% translated) - it is not a perfect metric, but it should give some hints for which languages translators community is the most active.

**Comment by justoverclockl** [comment]
@rob006 all languages are now added to packagists
